# Generated by Django 3.0.2 on 2020-03-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('guard', 'Guard'), ('forward', 'Forward'), ('center', 'Center')], default='Guard', max_length=7),
            preserve_default=False,
        ),
    ]
