# Generated by Django 3.0.2 on 2020-05-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_auto_20200423_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height_feet',
            field=models.IntegerField(choices=[(4, 4), (5, 5), (6, 6), (7, 7)], default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='height_inches',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(default=220),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Guard', 'Guard'), ('Forward', 'Forward'), ('Center', 'Center')], max_length=7),
        ),
    ]
