# Generated by Django 3.0.7 on 2020-08-20 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_auto_20200503_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
