# Generated by Django 3.0.2 on 2020-05-14 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('opponent', models.CharField(max_length=100)),
                ('home_away', models.CharField(choices=[('Home', 'Home'), ('Away', 'Away')], max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
