# Generated by Django 3.0.2 on 2020-08-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Done', 'Done')], max_length=15),
        ),
    ]
