# Generated by Django 3.0.2 on 2020-08-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('stat', models.CharField(max_length=100)),
            ],
        ),
    ]
