# Generated by Django 3.0.2 on 2020-08-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='game_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='player_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='result',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='x_pos',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='y_pos',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='zone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
