# Generated by Django 3.0.2 on 2020-08-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shot', '0002_auto_20200808_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
