# Generated by Django 3.0.7 on 2020-08-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_player_age'),
        ('shot', '0004_auto_20200820_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
    ]
