# Generated by Django 3.0.2 on 2020-02-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='team_location',
            field=models.CharField(default='empty location', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='team_name',
            field=models.CharField(default='empty name', max_length=100),
            preserve_default=False,
        ),
    ]
