# Generated by Django 3.0.2 on 2020-04-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='team_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
    ]
