# Generated by Django 3.0.2 on 2020-02-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200207_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='team_location',
            field=models.CharField(default='TEAM_LOCATION', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='team_name',
            field=models.CharField(default='TEAM_NAME', max_length=100),
        ),
    ]
