# Generated by Django 3.0.2 on 2020-06-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200511_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='team_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='team_name',
            field=models.CharField(max_length=100),
        ),
    ]
